In [77]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = np.array([[1, 2], [3, 2], [3, 5], [3, 1], [2, 1], [2, 5], [1, 5]])
data

array([[1, 2],
       [3, 2],
       [3, 5],
       [3, 1],
       [2, 1],
       [2, 5],
       [1, 5]])

In [3]:
data.shape

(7, 2)

In [6]:
data_cov = np.cov(data)

In [7]:
eig_val, eig_vec = np.linalg.eig(data_cov)

In [8]:
eig_val

array([ 0.00000000e+00,  1.80000000e+01,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -6.92812544e-16,  0.00000000e+00])

In [9]:
eig_vec

array([[-9.86013297e-01, -1.66666667e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -9.62250449e-02,
         0.00000000e+00],
       [-2.81718085e-02,  1.66666667e-01, -8.45154255e-01,
         1.29788497e-16,  3.24471242e-17,  9.62250449e-02,
        -1.46012059e-16],
       [ 5.63436170e-02, -3.33333333e-01, -1.55597309e-01,
         4.00000000e-01,  2.00000000e-01, -1.92450090e-01,
        -8.00000000e-01],
       [-5.63436170e-02,  3.33333333e-01,  1.55597309e-01,
         8.85714286e-01, -5.71428571e-02,  1.92450090e-01,
         2.28571429e-01],
       [-2.81718085e-02,  1.66666667e-01,  7.77986546e-02,
        -5.71428571e-02,  9.71428571e-01,  9.62250449e-02,
         1.14285714e-01],
       [ 8.45154255e-02, -5.00000000e-01,  3.66604036e-01,
        -5.62985828e-17, -1.40746457e-17,  8.66025404e-01,
         6.33359056e-17],
       [ 1.12687234e-01, -6.66666667e-01, -3.11194618e-01,
         2.28571429e-01,  1.14285714e-01, -3.84900179e-01,
         5.4285714

In [10]:
eig_vec.shape

(7, 7)

In [66]:
eig = eig_vec[2].reshape(1, -1)

In [67]:
np.dot(data.reshape(2,7), eig.T)

array([[-3.03936543],
       [-3.15837045]])

In [68]:
eig.reshape(-1, 1).shape

(7, 1)

In [69]:
data.reshape(2,7)

array([[1, 2, 3, 2, 3, 5, 3],
       [1, 2, 1, 2, 5, 1, 5]])

In [70]:
eig

array([[ 0.05634362, -0.33333333, -0.15559731,  0.4       ,  0.2       ,
        -0.19245009, -0.8       ]])

In [71]:
from sklearn.datasets import load_wine

In [72]:
wine = load_wine()

In [73]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [74]:
wine.data.shape

(178, 13)

In [75]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [78]:
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df["target"] = wine.target

In [79]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [80]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [84]:
df.iloc[158]

alcohol                          14.34
malic_acid                        1.68
ash                               2.70
alcalinity_of_ash                25.00
magnesium                        98.00
total_phenols                     2.80
flavanoids                        1.31
nonflavanoid_phenols              0.53
proanthocyanins                   2.70
color_intensity                  13.00
hue                               0.57
od280/od315_of_diluted_wines      1.96
proline                         660.00
target                            2.00
Name: 158, dtype: float64

In [85]:
from sklearn.decomposition import PCA

In [86]:
pc = PCA(n_components=2)

In [87]:
pc.fit_transform(df.drop("target", axis=1))

array([[ 3.18562979e+02,  2.14921307e+01],
       [ 3.03097420e+02, -5.36471768e+00],
       [ 4.38061133e+02, -6.53730945e+00],
       [ 7.33240139e+02,  1.92729032e-01],
       [-1.15714285e+01,  1.84899946e+01],
       [ 7.03231192e+02, -3.32158674e-01],
       [ 5.42971581e+02, -1.35189666e+01],
       [ 5.48401860e+02,  1.14494324e+01],
       [ 2.98036863e+02, -8.18015784e+00],
       [ 2.98049553e+02, -7.10154294e+00],
       [ 7.63079712e+02, -8.33431723e+00],
       [ 5.32943228e+02, -1.42876338e+01],
       [ 5.72834410e+02, -2.10050143e+01],
       [ 4.02925358e+02, -1.61026352e+01],
       [ 8.00053394e+02, -1.21184472e+01],
       [ 5.63245578e+02,  2.21482866e+00],
       [ 5.33379651e+02,  1.08048022e+01],
       [ 3.83317591e+02,  8.47741982e+00],
       [ 9.33118387e+02, -8.35447844e+00],
       [ 9.84031775e+01,  1.43926594e+01],
       [ 3.35935940e+01,  2.55679565e+01],
       [ 2.31464375e+01,  1.81747309e+00],
       [ 2.88093030e+02, -3.96304175e+00],
       [ 2.

In [88]:
pc1 = PCA(n_components=1)

In [89]:
pc1.fit_transform(data)

array([[-0.86273571],
       [-1.09146608],
       [ 1.88885026],
       [-2.08490486],
       [-1.97053967],
       [ 2.00321544],
       [ 2.11758062]])

In [97]:
data = np.array([[1, 2], [3, 2], [3, 5], [3, 1], [2, 1], [2, 5], [1, 5]])
data

array([[1, 2],
       [3, 2],
       [3, 5],
       [3, 1],
       [2, 1],
       [2, 5],
       [1, 5]])

In [98]:
from sklearn.preprocessing import StandardScaler

In [99]:
scalar = StandardScaler()

In [100]:
new_data = scalar.fit_transform(data)
new_data

array([[-1.37198868, -0.56407607],
       [ 1.02899151, -0.56407607],
       [ 1.02899151,  1.12815215],
       [ 1.02899151, -1.12815215],
       [-0.17149859, -1.12815215],
       [-0.17149859,  1.12815215],
       [-1.37198868,  1.12815215]])

In [102]:
cov_data = np.cov(new_data[:, 0], new_data[:, 1])
cov_data

array([[ 1.16666667, -0.22572258],
       [-0.22572258,  1.16666667]])

In [103]:
eig_val, eig_vec = np.linalg.eig(cov_data)

In [104]:
eig_val

array([1.39238925, 0.94094409])

In [105]:
eig_vec

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [106]:
pc = eig_vec[:1]

In [107]:
pc

array([[0.70710678, 0.70710678]])

In [108]:
data_tr = np.dot(new_data, pc.T)

In [109]:
data_tr

array([[-1.36900452],
       [ 0.32874486],
       [ 1.52533091],
       [-0.07011716],
       [-0.91899185],
       [ 0.67645622],
       [-0.17241846]])

In [110]:
pc2 = PCA(n_components=1)

In [111]:
pc2.fit_transform(new_data)

array([[ 0.57128048],
       [-1.12646889],
       [ 0.07011716],
       [-1.52533091],
       [-0.67645622],
       [ 0.91899185],
       [ 1.76786654]])

In [112]:
pc2.components_

array([[-0.70710678,  0.70710678]])